log_level: debug
port: 8000
address: "0.0.0.0"
threads: 8
static_resource_path: "../public/" 
views_path: "../views/" 
config_path: "../config/" 
dsn: "sqlite3://vuecrud_database.sqlite"
#dsn: "mysql://db=laravel_crud_api host=127.0.0.1 user=laravel_crud_api password='tWz0cvzDTvBE'"
cors_allow: "*"
